handled error inside run actions

diff --git a/.github/workflows/pull-master-release.yaml b/.github/workflows/pull-master-release.yaml
--- a/.github/workflows/pull-master-release.yaml
+++ b/.github/workflows/pull-master-release.yaml
@@ -73,7 +73,7 @@ jobs:
         run: make webpack-npm
 
       - name: Package kos-js
-        run: zip -r ./demo/kos-js.zip ./demo/kos
+        run: zip -r ./demo/kos-js.zip ./demo/kos || { echo 'Packaging failed'; exit 1; }
 
       - name: Capture Release Notes
         id: release_notes
@@ -85,7 +85,7 @@ jobs:
       - name: Create GitHub Release
         run: |
           VERSION=$(cat VERSION)
-          gh release create "v$VERSION" ./demo/kos-js.zip --title "Release v$VERSION" --notes "${{ steps.release_notes.outputs.notes }}"
+          gh release create "v$VERSION" ./demo/kos-js.zip --title "Release v$VERSION" --notes "${{ steps.release_notes.outputs.notes }}" || { echo 'Release creation failed'; exit 1; }
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
